version: "3.8"
services:
  db:
    image: mysql:8.3.0
    container_name: docker-mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: studentadmin_db
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - "3307:3306"
    volumes:
      - spring_db_data:/var/lib/mysql
volumes:
  spring_db_data: